# Generated by Django 5.1.5 on 2025-02-01 21:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('quotes', '0004_quote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='quote',
            name='tags',
        ),
    ]
